server:
  port: 8080

spring:
  application:
    name: api-gateway
  #cloud:
    #gateway:
      #mvc:
        #routes:
          #- id: ${name}-service
            #uri: lb://${name}-service
            #predicates:
              #- Path=/api/v1/${api-name}
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            - Trace
            - route:
              RouteDefinitionLocator: INFO
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka